### ISSUE TITLE
markdown test

### ISSUE THREAD

**Issue by lanten** [lanten/blog#2]
[banner]: http://img5.imgtn.bdimg.com/it/u=283059571,1584484264&fm=27&gp=0.jpg

## Title

> sub title `alert(123)`

- list item 1
- list item 2
- list item 3

```js
// codes
    componentDidMount() {
      // console.log('loading', $app.nav)
      $app.nav.loader(true)
      importComponent().then(({ default: comp }) => {
        this.setState({ comp }, () => {
          $app.nav.loader(false)
        })
      });
    }
```

## sass

```scss
@import'./var.scss';
.layout {
  padding-top: $height_header + $padding;
  @media #{$max_xs} {
    padding-top: $height_header + $padding/2;
  }
  .container {
    margin: 0 auto;
    max-width: $width_container;
    padding: 0 $padding;
    @media #{$max_xs} {
      padding: 0 $padding/2
    }
  }
}
```

![img](http://img5.imgtn.bdimg.com/it/u=283059571,1584484264&fm=27&gp=0.jpg)
